// 20251116020000_alter_aeronaves_prefixo_unique_index.js

exports.up = async function(knex) {
  await knex.schema.table('aeronaves', (table) => {
    // Drop the existing unique constraint on 'prefixo'
    // The name of the constraint is usually generated by Knex as table_column_unique
    table.dropUnique(['prefixo']);
  });

  // Add a new unique functional index for case-insensitive uniqueness
  return knex.schema.raw('CREATE UNIQUE INDEX aeronaves_prefixo_upper_unique ON aeronaves (UPPER(prefixo));');
};

exports.down = async function(knex) {
  // Drop the new unique functional index
  await knex.schema.raw('DROP INDEX aeronaves_prefixo_upper_unique;');

  // Add the original unique constraint back (case-sensitive)
  return knex.schema.table('aeronaves', (table) => {
    table.unique(['prefixo']);
  });
};
